const CENTER=[-58.515,-34.526];
const STORAGE="observatorio-real-points";
let map=null,marker=null,selectedPoint=null,activeCategory="all",draftAlert=null;
let mapReady=false;
const card=document.querySelector("#point-card"),categoryCard=document.querySelector("#category-card");
const coords=document.querySelector("#coords"),addressEl=document.querySelector("#address"),placeEl=document.querySelector("#place");
const categories=[
{id:"transito",icon:"🚦",name:"Tránsito",color:"#258bd6",sub:["Bache / calzada rota","Semáforo","Estacionamiento indebido","Señalización","Obstrucción de calzada"]},
{id:"residuos",icon:"♻",name:"Residuos y limpieza",color:"#6b8e23",sub:["Basura acumulada","Basura reiterada","Recolección no realizada","Microbasural","Falta de limpieza"]},
{id:"defensa-civil",icon:"⚠",name:"Riesgo / Defensa Civil",color:"#d67b25",sub:["Cable caído","Poste peligroso","Elemento peligroso","Situación de riesgo"]},
{id:"alumbrado",icon:"☼",name:"Alumbrado",color:"#d6a925",sub:["Luz apagada","Luminaria dañada","Poste de alumbrado","Falla reiterada"]},
{id:"espacios-verdes",icon:"🌳",name:"Espacios verdes",color:"#3d9b62",sub:["Rama peligrosa","Poda necesaria","Árbol caído","Espacio verde deteriorado","Falta de mantenimiento"]},
{id:"accesibilidad",icon:"♿",name:"Accesibilidad",color:"#7b61a8",sub:["Rampa bloqueada","Vereda inaccesible","Obstáculo permanente"]},
{id:"infraestructura",icon:"🏗",name:"Infraestructura",color:"#7b8794",sub:["Vereda dañada","Obra deteriorada","Mobiliario urbano dañado"]},
{id:"agua",icon:"💧",name:"Agua / saneamiento",color:"#2499b5",sub:["Pérdida de agua","Inundación / anegamiento","Desagüe obstruido","Problema de drenaje"]},
{id:"servicios",icon:"◎",name:"Servicios públicos",color:"#a05a9b",sub:["Servicio no realizado","Servicio defectuoso","Falla reiterada"]},
{id:"seguridad",icon:"🛡",name:"Seguridad / incidentes",color:"#b84a4a",sub:["Robos reiterados","Intentos de robo","Hurtos reiterados","Daños a propiedad","Incidentes en transporte","Zona de riesgo"]}
];
const conditions=[{id:"problema",icon:"⚠",name:"Hay un problema"},{id:"no-funciona",icon:"⛔",name:"No funciona"},{id:"roto",icon:"🔧",name:"Está roto / dañado"},{id:"no-sirve",icon:"✕",name:"No sirve / no cumple"}];
function loadPoints(){try{return JSON.parse(localStorage.getItem(STORAGE)||"[]")}catch{return[]}}
function points(){return loadPoints()}
function savePoints(v){localStorage.setItem(STORAGE,JSON.stringify(v))}
function announce(message){const el=document.querySelector("#global-status");if(el)el.textContent=message}
function setAppStatus(message,ok=true){const el=document.querySelector("#app-status");if(!el)return;el.innerHTML=`<i></i><span>${message}</span>`;el.classList.toggle("status-error",!ok)}
function makeId(){return crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2)}
function confidenceLabel(p){const v=Number(p?.confidence||0),d=Number(p?.dataCount||0),e=Array.isArray(p?.evidence)?p.evidence.length:0;if(v>=5||d>=5||e>=2)return "Dato respaldado";if(v>=2||d>=2||e>=1)return "Dato corroborado";return "Dato informado"}
function updatePointConfidence(p){const el=document.querySelector("#point-confidence"),btn=document.querySelector("#confirm-point");if(!el)return;el.classList.toggle("hidden",!p?.id);if(p?.id)el.innerHTML="<strong>"+confidenceLabel(p)+"</strong><span>"+Number(p.confirmations||0)+" corroboraciones · "+Number(p.dataCount||0)+" aportes · "+(Array.isArray(p.evidence)?p.evidence.length:0)+" evidencias</span>";if(btn){btn.classList.toggle("hidden",!p?.id);btn.dataset.pointId=p?.id||""}}
function showPoint(p){coords.textContent=`Coordenadas: ${Number(p.lat).toFixed(6)}, ${Number(p.lng).toFixed(6)}`;card.classList.remove("hidden");const c=document.querySelector("#contribute-point");if(c)c.classList.toggle("hidden",!p.id);const full=p.id?loadPoints().find(x=>x.id===p.id):p;updatePointConfidence(full||p)}
function clearPoint(){if(marker){marker.remove();marker=null}selectedPoint=null;draftAlert=null;card.classList.add("hidden");categoryCard.classList.add("hidden")}
function setMarker(lng,lat,id=null){if(marker)marker.remove();marker=new maplibregl.Marker({color:"#258bd6"}).setLngLat([lng,lat]).addTo(map);selectedPoint={lat:Number(lat),lng:Number(lng),id:id||null};showPoint(selectedPoint)}
async function reverseGeocode(lat,lng){try{const res=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lng}&zoom=18&addressdetails=1`,{headers:{Accept:"application/json"}});if(!res.ok)throw Error();const d=await res.json(),a=d.address||{};addressEl.textContent=d.display_name||"Dirección no disponible";placeEl.textContent=[a.city||a.town||a.village||a.municipality||"",a.county||a.state_district||""].filter(Boolean).join(" · ")}catch{addressEl.textContent="Dirección no disponible";placeEl.textContent=""}}
function categoryUI(){const grid=document.querySelector("#category-grid");if(!grid)return;grid.className="category-grid floating-menu";grid.innerHTML="";categories.forEach(c=>{const b=document.createElement("button");b.type="button";b.className="category-button floating-option";b.style.setProperty("--item-color",c.color);b.innerHTML=`<span class="category-icon">${c.icon}</span><span>${c.name}</span>`;b.onclick=()=>openSubcategory(c);grid.appendChild(b)})}
function openSubcategory(category){const grid=document.querySelector("#category-grid");grid.className="category-grid floating-menu sub-floating";grid.innerHTML=`<div class="subcategory-head floating-head"><button type="button" class="floating-back" id="back-categories">‹</button><span class="category-icon large">${category.icon}</span><strong>${category.name}</strong></div><div class="subcategory-note">Elegí qué problema querés registrar.</div>`;category.sub.forEach(name=>{const b=document.createElement("button");b.type="button";b.className="subcategory-button floating-option";b.style.setProperty("--item-color",category.color);b.innerHTML=`<span class="sub-icon">${category.icon}</span><span>${name}</span>`;b.onclick=()=>openCondition(category,name);grid.appendChild(b)});document.querySelector("#back-categories").onclick=categoryUI}
function openCondition(category,subtype){const grid=document.querySelector("#category-grid");grid.className="category-grid floating-menu condition-menu";grid.innerHTML=`<div class="subcategory-head floating-head"><button type="button" class="floating-back" id="back-subcategories">‹</button><span class="category-icon large">${category.icon}</span><strong>${subtype}</strong></div><div class="subcategory-note">Indicá qué ocurre.</div>`;conditions.forEach(c=>{const b=document.createElement("button");b.type="button";b.className="subcategory-button floating-option condition-option";b.style.setProperty("--item-color",category.color);b.innerHTML=`<span class="sub-icon">${c.icon}</span><span>${c.name}</span>`;b.onclick=()=>openReportForm(category,subtype,c);grid.appendChild(b)});document.querySelector("#back-subcategories").onclick=()=>openSubcategory(category)}
function openReportForm(category,subtype,condition){const grid=document.querySelector("#category-grid");draftAlert={category,subtype,condition};grid.className="report-form";grid.innerHTML=`<div class="subcategory-head floating-head"><button type="button" id="back-condition" class="floating-back">‹</button><span class="category-icon large">${condition.icon}</span><strong>${subtype}</strong></div><div class="selected-condition">${condition.name}</div><label>Descripción<textarea id="report-description" rows="3" placeholder="Contá qué sucede en este lugar..."></textarea></label><label>Propuesta<textarea id="report-proposal" rows="3" placeholder="¿Qué proponés para solucionarlo?"></textarea></label><label class="evidence-label">Pruebas <span>Foto, video o documento</span><input id="report-evidence" type="file" accept="image/*,video/*,.pdf" multiple></label><button id="publish-report" class="save-button publish-button" type="button">Publicar alerta</button>`;document.querySelector("#back-condition").onclick=()=>openCondition(category,subtype);document.querySelector("#publish-report").onclick=()=>publishPoint(category,subtype,condition)}
function publishPoint(category,subtype,condition){if(!selectedPoint||!draftAlert)return;const now=new Date().toISOString(),description=document.querySelector("#report-description")?.value.trim()||"",proposal=document.querySelector("#report-proposal")?.value.trim()||"",files=[...(document.querySelector("#report-evidence")?.files||[])].map(f=>({name:f.name,type:f.type,size:f.size}));const p={id:makeId(),createdAt:now,updatedAt:now,votes:0,confirmations:0,dataCount:0,confidence:0,lat:selectedPoint.lat,lng:selectedPoint.lng,address:addressEl.textContent||"Dirección no disponible",place:placeEl.textContent||"",category:category.id,categoryName:category.name,subtype,condition:condition.name,status:"activo",alertType:"permanente_recurrente",source:"aporte_ciudadano",description,proposal,evidence:files,history:[{at:now,type:"status",value:"alerta activa",source:"aporte_ciudadano"}]};const ps=loadPoints();ps.push(p);savePoints(ps);categoryCard.classList.add("hidden");card.classList.add("hidden");if(marker){marker.remove();marker=null}selectedPoint=null;draftAlert=null;refreshReports();refreshHistory();updateDashboardKpis()}
function renderCategoryFilter(){const wrap=document.querySelector("#category-filter");if(!wrap)return;wrap.innerHTML="";const all=document.createElement("button");all.type="button";all.className="filter-chip active";all.textContent="Todos";all.dataset.category="all";wrap.appendChild(all);categories.forEach(c=>{const b=document.createElement("button");b.type="button";b.className="filter-chip";b.textContent=c.name;b.dataset.category=c.id;b.style.setProperty("--chip-color",c.color);wrap.appendChild(b)});wrap.onclick=e=>{const b=e.target.closest(".filter-chip");if(!b)return;activeCategory=b.dataset.category;wrap.querySelectorAll(".filter-chip").forEach(x=>x.classList.toggle("active",x===b));refreshReports();applyMapFilter()}}
function applyMapFilter(){if(!map)return;categories.forEach(c=>{const visible=activeCategory==="all"||activeCategory===c.id;["report-clusters-"+c.id,"report-cluster-count-"+c.id,"report-points-"+c.id].forEach(id=>{if(map.getLayer(id))map.setLayoutProperty(id,"visibility",visible?"visible":"none")})});updateDashboardKpis()}
function refreshReports(){if(!map||!map.isStyleLoaded())return;const ps=loadPoints();categories.forEach(c=>{const src=map.getSource("reports-"+c.id);if(src)src.setData({type:"FeatureCollection",features:ps.filter(p=>p.category===c.id).map(p=>({type:"Feature",geometry:{type:"Point",coordinates:[Number(p.lng),Number(p.lat)]},properties:{id:p.id,category:p.categoryName,status:p.status,categoryId:p.category}}))})})}
function addReportLayers(){categories.forEach(c=>{const sid="reports-"+c.id;if(map.getSource(sid))return;const cid="report-clusters-"+c.id,nid="report-cluster-count-"+c.id,pid="report-points-"+c.id;map.addSource(sid,{type:"geojson",data:{type:"FeatureCollection",features:[]},cluster:true,clusterMaxZoom:16,clusterRadius:48});map.addLayer({id:cid,type:"circle",source:sid,filter:["has","point_count"],paint:{"circle-radius":["step",["get","point_count"],20,10,26,50,32],"circle-color":c.color,"circle-opacity":.9,"circle-stroke-width":2,"circle-stroke-color":"#fff"}});map.addLayer({id:nid,type:"symbol",source:sid,filter:["has","point_count"],layout:{"text-field":["get","point_count_abbreviated"],"text-size":12},paint:{"text-color":"#fff"}});map.addLayer({id:pid,type:"circle",source:sid,filter:["!",["has","point_count"]],paint:{"circle-radius":7,"circle-color":c.color,"circle-stroke-color":"#fff","circle-stroke-width":2}});map.on("click",pid,e=>{const f=e.features?.[0];if(!f)return;const p=loadPoints().find(x=>x.id===f.properties.id);if(p){map.flyTo({center:[p.lng,p.lat],zoom:17,pitch:35});setMarker(p.lng,p.lat,p.id);addressEl.textContent=p.address||"Dirección no disponible";placeEl.textContent=p.place||""}});map.on("click",cid,e=>{const f=e.features?.[0];if(!f)return;map.getSource(sid).getClusterExpansionZoom(f.properties.cluster_id,(err,z)=>{if(!err)map.easeTo({center:f.geometry.coordinates,zoom:z})})})})}
function openExistingPoint(id,contribute=false){const p=loadPoints().find(x=>x.id===id);if(!p)return;document.querySelector("#mapa")?.scrollIntoView({behavior:"smooth"});setTimeout(()=>{if(!map)return;map.flyTo({center:[p.lng,p.lat],zoom:17,pitch:35,duration:700});setMarker(p.lng,p.lat,p.id);addressEl.textContent=p.address||"Dirección no disponible";placeEl.textContent=p.place||"";if(contribute)setTimeout(openContribution,120)},350)}
const OR_CONTRIBUTE_FIX_V1=true;
function openContribution(){const p=selectedPoint?.id?loadPoints().find(x=>x.id===selectedPoint.id):null;if(!p)return;const grid=document.querySelector("#category-grid");categoryCard.classList.remove("hidden");grid.className="report-form";grid.innerHTML=`<div class="subcategory-head floating-head"><button type="button" id="back-contribution" class="floating-back">‹</button><span class="category-icon large">＋</span><strong>Aportar datos</strong></div><div class="selected-condition">Alerta existente</div><label>Nuevo dato<textarea id="contribution-text" rows="3" placeholder="Contá qué dato nuevo querés aportar..."></textarea></label><label>Pruebas <span>Foto, video o documento</span><input id="contribution-evidence" type="file" accept="image/*,video/*,.pdf" multiple></label><button id="publish-contribution" class="save-button publish-button" type="button">Aportar datos</button>`;document.querySelector("#back-contribution").onclick=()=>categoryCard.classList.add("hidden");document.querySelector("#publish-contribution").onclick=()=>{const text=document.querySelector("#contribution-text")?.value.trim()||"",files=[...(document.querySelector("#contribution-evidence")?.files||[])].map(f=>({name:f.name,type:f.type,size:f.size}));if(!text&&!files.length)return;const ps=loadPoints(),target=ps.find(x=>x.id===p.id);if(!target)return;const now=new Date().toISOString();target.dataCount=Number(target.dataCount||0)+1;target.confidence=Number(target.confirmations||0)+Number(target.dataCount||0);target.updatedAt=now;target.history=target.history||[];target.history.push({at:now,type:"data",value:"dato aportado",source:"aporte_ciudadano",text,evidence:files});savePoints(ps);categoryCard.classList.add("hidden");refreshReports();refreshHistory();updateDashboardKpis()}}
function fmtDate(iso){return new Intl.DateTimeFormat("es-AR",{dateStyle:"short",timeStyle:"short"}).format(new Date(iso))}
function updateDashboardKpis(){const el=document.querySelector("#dashboard-kpis");if(!el)return;const ps=loadPoints(),active=ps.filter(p=>p.status!=="resuelto").length,resolved=ps.filter(p=>p.status==="resuelto").length,votes=ps.reduce((n,p)=>n+Number(p.votes||0),0),data=ps.reduce((n,p)=>n+Number(p.dataCount||0),0),confirmed=ps.reduce((n,p)=>n+Number(p.confirmations||0),0);el.innerHTML=[["Reportes",ps.length,"puntos registrados"],["Activos",active,"situaciones abiertas"],["Resueltos",resolved,"casos con cierre"],["Corroboraciones",confirmed,"validaciones ciudadanas"],["Aportes",data,"nuevos datos"],["Votos",votes,"apoyos registrados"]].map(([a,b,c])=>`<article class="kpi-card"><span>${a}</span><strong>${b}</strong><small>${c}</small></article>`).join("")}
function refreshHistory(){const list=document.querySelector("#history-list");if(!list)return;const ps=loadPoints().sort((a,b)=>new Date(b.updatedAt||b.createdAt)-new Date(a.updatedAt||a.createdAt));if(!ps.length){list.innerHTML='<div class="empty-state"><strong>Aún no hay datos publicados</strong><span>Marcá un punto en el mapa para crear el primer registro del territorio.</span></div>';updateDashboardKpis();return}list.innerHTML=ps.map(p=>`<article class="history-card" data-point-id="${p.id}" tabindex="0" role="button"><div class="history-main"><strong>${p.categoryName}</strong><small>${p.subtype||""} · ${p.condition||""}</small><span class="status-pill">${p.status}</span><span class="confidence-pill">${confidenceLabel(p)} · ${Number(p.confirmations||0)} corroboraciones</span><small>${p.address||"Ubicación sin dirección"}</small><small>${Number(p.lat).toFixed(6)}, ${Number(p.lng).toFixed(6)}</small>${p.description?`<small>${p.description}</small>`:""}${p.proposal?`<small>Propuesta: ${p.proposal}</small>`:""}</div><div class="timeline">${(p.history||[]).map(e=>`<div><b>${e.value}</b><span>${fmtDate(e.at)} · ${e.source}</span></div>`).join("")}</div></article>`).join("");list.querySelectorAll(".history-card").forEach(el=>{const open=()=>openExistingPoint(el.dataset.pointId);el.onclick=open;el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open()}}})}
async function searchAddress(){const input=document.querySelector("#address-search"),results=document.querySelector("#search-results"),q=input?.value.trim();if(!q)return;results.classList.remove("hidden");results.textContent="Buscando…";try{const res=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=5&q=${encodeURIComponent(q.toLowerCase().includes("argentina")?q:q+", Argentina")}`,{headers:{Accept:"application/json"}});if(!res.ok)throw Error();const data=await res.json();results.innerHTML="";if(!data.length){results.textContent="No encontramos esa dirección.";return}data.forEach(item=>{const b=document.createElement("button");b.type="button";b.textContent=item.display_name;b.onclick=()=>{const lng=Number(item.lon),lat=Number(item.lat);map.flyTo({center:[lng,lat],zoom:17,pitch:35});setMarker(lng,lat);reverseGeocode(lat,lng);results.classList.add("hidden")};results.appendChild(b)})}catch{results.textContent="No se pudo buscar ahora. Podés marcar el punto directamente sobre el mapa."}}
function injectVoteStyle(){const s=document.createElement("style");s.textContent="#dashboard-vote{background:#e8f7ed!important;border:1px solid #43a866!important;color:#16803b!important;font-weight:800!important}#dashboard-vote:hover{background:#d8f1df!important}#history-list .history-card{cursor:pointer}#history-list .history-card:focus-visible{outline:2px solid #258bd6;outline-offset:2px}";document.head.appendChild(s)}
function init(){if(typeof maplibregl==="undefined"){const m=document.querySelector("#map");if(m)m.innerHTML="<div class='map-error' role='alert'><strong>No se pudo cargar el motor del mapa.</strong><span>Revisá tu conexión e intentá nuevamente.</span></div>";setAppStatus("Mapa no disponible",false);announce("No se pudo cargar el mapa.");return}injectVoteStyle();categoryUI();renderCategoryFilter();map=new maplibregl.Map({container:"map",style:"https://tiles.openfreemap.org/styles/liberty",center:CENTER,zoom:13,pitch:35,bearing:0,attributionControl:true,cooperativeGestures:false});
map.on("error",()=>{if(!mapReady){setAppStatus("No se pudo cargar el mapa",false);announce("El mapa informó un error de carga.")}});map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),"top-right");map.on("load",()=>{mapReady=true;map.resize();addReportLayers();refreshReports();applyMapFilter();document.querySelector("#map-loading")?.classList.add("hidden");setAppStatus("Mapa activo",true);announce("Mapa listo. Tocá un punto para comenzar.");});map.on("click",e=>{if(e.defaultPrevented)return;setMarker(e.lngLat.lng,e.lngLat.lat);reverseGeocode(e.lngLat.lat,e.lngLat.lng)});document.querySelector("#clear-point")?.addEventListener("click",clearPoint);
document.querySelectorAll(".main-nav a").forEach(link=>link.addEventListener("click",()=>{document.querySelectorAll(".main-nav a").forEach(x=>x.classList.remove("active"));link.classList.add("active")}));document.querySelector("#contribute-point")?.addEventListener("click",openContribution);document.querySelector("#confirm-point")?.addEventListener("click",()=>{const id=document.querySelector("#confirm-point")?.dataset.pointId;if(!id)return;const ps=loadPoints(),p=ps.find(x=>x.id===id);if(!p)return;const key="observatorio-real-confirmed-"+id;if(localStorage.getItem(key))return;const now=new Date().toISOString();p.confirmations=Number(p.confirmations||0)+1;p.confidence=Number(p.confirmations||0)+Number(p.dataCount||0);p.updatedAt=now;p.history=p.history||[];p.history.push({at:now,type:"confirmation",value:"dato corroborado por un par",source:"corroboracion_ciudadana"});savePoints(ps);localStorage.setItem(key,"1");showPoint(p);refreshHistory();refreshReports()});document.querySelector("#close-category")?.addEventListener("click",()=>categoryCard.classList.add("hidden"));document.querySelector("#save-point")?.addEventListener("click",()=>{if(!selectedPoint)return;categoryCard.classList.remove("hidden");categoryUI()});document.querySelector("#locate")?.addEventListener("click",()=>{if(!navigator.geolocation)return alert("La ubicación no está disponible en este dispositivo.");navigator.geolocation.getCurrentPosition(pos=>{const {latitude:lat,longitude:lng}=pos.coords;map.flyTo({center:[lng,lat],zoom:16,pitch:45,duration:800});setMarker(lng,lat);reverseGeocode(lat,lng)},()=>alert("No se pudo obtener la ubicación. Podés marcar el punto directamente sobre el mapa."),{enableHighAccuracy:true,timeout:10000,maximumAge:60000})});document.querySelector("#search-button")?.addEventListener("click",searchAddress);document.querySelector("#address-search")?.addEventListener("keydown",e=>{if(e.key==="Enter")searchAddress()});refreshHistory()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();