document.documentElement.dataset.app="observatorio-real";
const KEY="observatorio-real-local-history";
const form=document.querySelector("#report-form"),list=document.querySelector("#history-list"),result=document.querySelector("#report-result"),count=document.querySelector("#cases-count");
function loadReports(){try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}}
function saveReports(r){localStorage.setItem(KEY,JSON.stringify(r))}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function renderHistory(){const reports=loadReports();if(count)count.textContent=reports.length;if(!reports.length){list.innerHTML='<div class="history-empty">Todavía no hay registros en este dispositivo. El primer registro inicia la historia.</div>';return}list.innerHTML=reports.slice().reverse().map(r=>'<article class="history-item"><strong>#'+r.id+' · '+escapeHtml(r.title)+'</strong><span>Registrado '+new Date(r.createdAt).toLocaleString("es-AR")+' · '+(r.lat||"sin latitud")+', '+(r.lon||"sin longitud")+'</span><p>'+escapeHtml(r.description||"Sin descripción.")+'</p></article>').join("")}
form?.addEventListener("submit",e=>{e.preventDefault();const title=document.querySelector("#report-title").value.trim(),description=document.querySelector("#report-description").value.trim(),lat=document.querySelector("#report-lat").value.trim(),lon=document.querySelector("#report-lon").value.trim(),reports=loadReports(),id=String(Date.now()).slice(-8),now=new Date().toISOString();reports.push({id,title,description,lat,lon,createdAt:now,status:"reportado",history:[{status:"reportado",at:now}]});saveReports(reports);form.reset();result.textContent="Registro #"+id+" guardado en este dispositivo.";renderHistory()});
document.querySelector("#locate")?.addEventListener("click",()=>{if(!navigator.geolocation){result.textContent="Este dispositivo no permite geolocalización.";return}result.textContent="Buscando ubicación…";navigator.geolocation.getCurrentPosition(pos=>{document.querySelector("#report-lat").value=pos.coords.latitude.toFixed(6);document.querySelector("#report-lon").value=pos.coords.longitude.toFixed(6);result.textContent="Ubicación cargada. Revisala antes de guardar."},()=>{result.textContent="No se pudo obtener la ubicación."},{enableHighAccuracy:true,timeout:10000})});
renderHistory();