create extension if not exists postgis;
create extension if not exists pgcrypto;
create table if not exists public.reports(id uuid primary key default gen_random_uuid(),location geography(Point,4326) not null,category text not null,magnitude smallint not null check(magnitude between 1 and 5),description text,evidence_urls text[] default '{}',status text not null default 'pendiente' check(status in ('pendiente','verificado')),corroborations int not null default 0,created_at timestamptz not null default now());
create index if not exists reports_location_gix on public.reports using gist(location);
create table if not exists public.corroborations(report_id uuid references public.reports(id) on delete cascade,user_id uuid not null,created_at timestamptz not null default now(),primary key(report_id,user_id));
create or replace view public.reports_geo as select id,st_x(location::geometry) as lng,st_y(location::geometry) as lat,category,magnitude,description,evidence_urls,status,corroborations,created_at from public.reports;
create or replace function public.create_report(p_lng double precision,p_lat double precision,p_category text,p_magnitude smallint,p_description text,p_evidence_urls text[]) returns uuid language plpgsql security definer set search_path=public as $$ declare rid uuid; begin if auth.uid() is null then raise exception 'Authentication required'; end if; insert into reports(location,category,magnitude,description,evidence_urls) values(st_setsrid(st_makepoint(p_lng,p_lat),4326)::geography,p_category,p_magnitude,p_description,coalesce(p_evidence_urls,'{}')) returning id into rid; return rid; end $$;
create or replace function public.bump_corroboration() returns trigger language plpgsql security definer set search_path=public as $$ begin update reports set corroborations=corroborations+1,status=case when corroborations+1>=3 then 'verificado' else status end where id=new.report_id; return new; end $$;
drop trigger if exists trg_corroboration on public.corroborations;
create trigger trg_corroboration after insert on public.corroborations for each row execute function public.bump_corroboration();
alter table public.reports enable row level security;alter table public.corroborations enable row level security;
drop policy if exists reports_public_read on public.reports;create policy reports_public_read on public.reports for select using(true);
drop policy if exists reports_public_insert on public.reports;create policy reports_public_insert on public.reports for insert with check(auth.role()='authenticated');
drop policy if exists corroborations_read on public.corroborations;create policy corroborations_read on public.corroborations for select using(true);
drop policy if exists corroborations_insert on public.corroborations;create policy corroborations_insert on public.corroborations for insert with check(auth.role()='authenticated' and auth.uid()=user_id);
create or replace function public.corroboration_guard() returns trigger language plpgsql security definer set search_path=public as $$ begin if exists(select 1 from corroborations where report_id=new.report_id and user_id=new.user_id) then raise exception 'Ya corroboraste este reporte'; end if; return new; end $$;
drop trigger if exists trg_corroboration_guard on public.corroborations;create trigger trg_corroboration_guard before insert on public.corroborations for each row execute function public.corroboration_guard();
grant select on public.reports_geo to anon,authenticated;
grant execute on function public.create_report(double precision,double precision,text,smallint,text,text[]) to anon,authenticated;
grant insert on public.corroborations to authenticated;
insert into storage.buckets(id,name,public) values('evidence','evidence',true) on conflict(id) do nothing;
drop policy if exists evidence_public_read on storage.objects;create policy evidence_public_read on storage.objects for select using(bucket_id='evidence');
drop policy if exists evidence_auth_upload on storage.objects;create policy evidence_auth_upload on storage.objects for insert to authenticated with check(bucket_id='evidence' and (storage.foldername(name))[1]=auth.uid()::text);